CREATE TABLE JOBS
(
    JOB_ID INT NOT NULL,
    JOB_TITLE INT,
    FIRST_NAME VARCHAR(5),
    LAST_NAME VARCHAR(5),
    DOB DATE,
    MIN_SALARY DECIMAL(10,2) NOT NULL,
    MAX_SALARY DECIMAL(20) NOT NULL,
    JOB_NAME INT,
)