REATE DATABASE EMPLOYEE;
CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DOB DATE,
    SALARY DECIMAL(4,2),
    EMPLOYEE_NAME INT NOT NULL,
)